<resources>
    <string name="app_name">Mr. Med</string>
    <string name="title_activity_main">MainActivity</string>

    <!--hear you can change currency-->
    <string name="rs">৳\u0020</string>
    <string name="discount_rs">Save Discount ৳\u0020</string>

    <string name="navigation_drawer_open">Open navigation drawer</string>
    <string name="navigation_drawer_close">Close navigation drawer</string>

    <string name="action_settings">Settings</string>

    <string name="error_field_required">This field is required</string>
    <string name="error_invalid_email">This email address is invalid</string>
    <string name="error_invalid_password">This password is too short</string>
    <string name="password_not_match">Conform password not match</string>
    <string name="phone_to_short">This Phone number is too short</string>
    <string name="error_invalid_date">This date is invalid</string>

    <string name="search_text">Search Medicine&#8230;</string>
    <string name="upload_your_prescription">Click to Upload Your Prescription</string>
    <string name="looking_for">What are you looking for?</string>
    <string name="suggested">Suggested</string>
    <string name="user_manage">User Management</string>
    <string name="user_profile">My Profile</string>
    <string name="my_orders">My Orders</string>
    <string name="upload_prescription">My Prescription Order</string>
    <string name="view_offer">Offers</string>
    <string name="product">Products</string>
    <string name="prescription">Prescription</string>
    <string name="medical_product">Medical Products</string>
    <string name="communicate">Communicate</string>
    <string name="rate_us">Rate Us</string>
    <string name="share">Share</string>
    <string name="logout">Logout</string>
    <string name="cart">Cart</string>
    <string name="add">ADD</string>
    <string name="qty">Qty:\u0020</string>
    <string name="search_prescription">Search Prescription</string>
    <string name="first_name">First Name</string>
    <string name="last_name">Last Name</string>
    <string name="email_address">Email Address</string>
    <string name="dob">Birth Date</string>
    <string name="mobile_number">Mobile Number</string>
    <string name="password">Password</string>
    <string name="confirm_password">Confirm Password</string>
    <string name="register_chk_note">Sign up to receive our special offers,updates and a lot more.</string>
    <string name="register">Register</string>
    <string name="sign_in">Sign In</string>
    <string name="forgot_note">Forgot your login details? Get help signing in.</string>
    <string name="sinup_note">Don\'t have an account? Sign up.</string>
    <string name="forgot_note_2">Enter the email address that you used to sign up on</string>
    <string name="submit">Submit</string>
    <string name="login">Login</string>
    <string name="reg_chk_note">Please Check our policy</string>
    <string name="upload_3_prescription">You can upload a total 3 prescriptions per order.</string>.
    <string name="please_upload_backside">Please Upload the Back-Side of your Prescription, if present.</string>
    <string name="details">Details</string>
    <string name="name">Name:\u0020</string>
    <string name="email_address_2">Email Address:\u0020</string>
    <string name="delivery_address">Delivery Address</string>
    <string name="no_address_found">No address found. Please add one.</string>
    <string name="billing_address">Billing Address</string>
    <string name="is_prescription_meant">Is prescription(s) meant for?</string>
    <string name="new_order">New Order</string>
    <string name="confirm">Confirm</string>
    <string name="registration_successfull">Registration Successful</string>
    <string name="available_products">Available Products:\u0020</string>
    <string name="record_not_found">Record Not Found</string>
    <string name="search">Search</string>
    <string name="generic_available">Generic Available</string>
    <string name="generic_not_available">Generic Not Available</string>
    <string name="in_stock">IN STOCK:\u0020</string>
    <string name="update">Update</string>
    <string name="cart_empty">Cart is empty</string>
    <string name="process_to_payment">Process to payment</string>
    <string name="enter_promo_code">Enter Coupon Code</string>
    <string name="apply">Apply</string>
    <string name="order_total">Order Total</string>
    <string name="subtotal">Subtotal</string>
    <string name="shipping_charges">Shipping Charges?</string>
    <string name="you_saved">You Saved:\u0020</string>
    <string name="discout">\u0020( Discount )</string>
    <string name="price_details">Price Details</string>
    <string name="remove">Remove</string>
    <string name="add_photo">Add Photo!</string>
    <string name="take_photo">Take Photo</string>
    <string name="choose_from_library">Choose from Library</string>
    <string name="cancel">@android:string/cancel</string>
    <string name="profile_pic_updated">Profile Picture Updated Successfully</string>
    <string name="city">City</string>
    <string name="address">Address</string>
    <string name="male">Male</string>
    <string name="fem